# Arquivo: nginx.conf
server {
  # O servidor escuta na porta 80
  listen 80;

  # Define a raiz onde os arquivos do Angular estão localizados
  root /usr/share/nginx/html;

  # Define o arquivo de entrada principal
  index index.html;

  # Configuração de localização principal
  location / {
    # Esta linha é a chave para o roteamento de SPAs (Single Page Applications).
    # Se o Nginx não encontrar um arquivo ou diretório correspondente à URL,
    # ele servirá o index.html. Isso permite que o roteador do Angular
    # assuma o controle e exiba a página correta.
    try_files $uri $uri/ /index.html;
  }
}
